[db]
host = "localhost"
port = 5432
user = "postgres"
name = "bot_db"

[wp]
user = "Furio"
url = "http://my-test-site.local"

[api]
base_url = "http://localhost:8000/api/v1"

[portmone]
payee_id = "1185"
gateway_url = "https://www.portmone.com.ua/gateway/"

[logs]
project_name = "telegram_bot"
show_datetime = true
datetime_format = "%Y-%m-%d %H:%M:%S"
show_debug_logs = false
time_in_utc = false
use_colors_in_console = true
renderer = "console"  # "console" or "json"
allow_third_party_logs = true